import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
import os

def send_email(file_path):

    sender_email = "gajendra.kumar@impressico.com"
    app_password = os.getenv("EMAIL_PASSWORD")

    receiver_emails = [
        "gajendra.kumar@impressico.com"
       # "harsh.kumar@impressico.com",
        #"nishant.sah@impressico.com"
        #"gajendarpundir44@gmail.com"
        ]

    message = MIMEMultipart("mixed")

    message["Subject"] = "📈 Top Buy Opportunities"
    message["From"] = sender_email
    message["To"] = ", ".join(receiver_emails)

    html = """
    <html>
    <body>
    <h3>Top 10 Buy Opportunities Report</h3>

    <p>Hello Team,</p>

    <p>Please find today's Top 10 Buy Opportunities generated by the Stock Scanner.</p>

    <p>The detailed Excel report is attached.</p>

    <br>

    <p>
    Regards,<br>
    <b>Gajendra Kumar (GK)</b><br>
    Sr. Data Engineer | Stock Market Enthusiast<br>
    Creator - Python Stock Scanner
    </p>

    </body>
    </html>
    """

    body_part = MIMEMultipart("alternative")
    body_part.attach(MIMEText(html, "html"))

    message.attach(body_part)

    with open(file_path, "rb") as attachment:
        part = MIMEBase("application",
                        "octet-stream"
                        )
        part.set_payload(
            attachment.read()
        )
    encoders.encode_base64(part)

    filename = os.path.basename(file_path)
    part.add_header("Content-Disposition",
                    f'attachment; filename= {file_path}'
                    )

    message.attach(part)

    with smtplib.SMTP_SSL("smtp.gmail.com",
                          465
                          ) as server:
        server.login(
            sender_email,
            app_password
        )

        server.sendmail(
            sender_email,
            receiver_emails,
            message.as_string()
        )
        print("Email Sent Successfully")
